# Generated by Django 4.2.5 on 2023-10-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(default='Joe', max_length=100),
        ),
    ]
