# Generated by Django 4.2.5 on 2023-10-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_event_host'),
        ('planner', '0002_rsvp'),
    ]

    operations = [
    ]
