# Generated by Django 4.2.5 on 2023-10-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_merge_0002_event_host_0002_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Lorem ipsum blah blah blah', max_length=1000),
        ),
    ]
