# Generated by Django 4.2.5 on 2023-11-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_rsvp_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.task'),
        ),
    ]
