# Generated by Django 4.1.7 on 2023-11-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_rsvp_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='task',
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.event'),
        ),
    ]
