# Generated by Django 4.1.7 on 2023-11-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_rsvp_task_alter_rsvp_event_alter_task_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planner.event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planner.event'),
        ),
    ]
