# Generated by Django 4.1.7 on 2023-11-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_rsvp_event_alter_task_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planner.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
