# Generated by Django 4.1.7 on 2023-11-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_rsvp_task_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.task'),
        ),
    ]
