# Generated by Django 4.1.7 on 2023-11-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_remove_rsvp_task_task_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='RSVP',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.task'),
        ),
    ]
