# Generated by Django 4.2.6 on 2023-11-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
