# Generated by Django 4.2.5 on 2023-11-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_event_date_alter_event_time'),
        ('planner', '0018_remove_event_created_by'),
    ]

    operations = [
    ]
