# Generated by Django 4.2.5 on 2023-11-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_merge_20231128_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
