# Generated by Django 4.1.7 on 2023-11-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_rsvp_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
    ]
