# Generated by Django 4.1.7 on 2023-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completedTasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='totalTasks',
            field=models.IntegerField(default=0),
        ),
    ]
