# Generated by Django 4.2.5 on 2023-11-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_merge_20231128_0159'),
        ('planner', '0022_event_completedtasks_event_totaltasks'),
    ]

    operations = [
    ]
