# Generated by Django 4.2.6 on 2023-12-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_merge_20231130_1926'),
        ('planner', '0030_alter_rsvp_unique_together_remove_rsvp_user'),
    ]

    operations = [
    ]
