# Generated by Django 4.2.5 on 2023-12-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_remove_event_host'),
        ('planner', '0035_rename_status_rsvp_rsvp'),
    ]

    operations = [
    ]
